prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'cloudwatch-exporter'
        static_configs:
          - targets: ['cloudwatch-exporter.monitoring.svc.cluster.local:9106']
