
apiVersion: v1
kind: ConfigMap
metadata:
  name: dump-config
data:
  DB_HOST: mariadb-2a.c566mcwwy70y.ap-northeast-2.rds.amazonaws.com
  DB_NAME: lovebridgedb
  GCP_BUCKET_NAME: lovebridge-db-backups



